# Generated by Django 5.0.4 on 2024-04-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_alter_mail_client_alter_mail_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='client',
        ),
        migrations.AddField(
            model_name='mail',
            name='client',
            field=models.ManyToManyField(to='newsletter.client', verbose_name='Клиент'),
        ),
    ]
