# Generated by Django 5.0.4 on 2024-04-21 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_remove_mail_client_mail_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.message', verbose_name='Сообщение'),
        ),
    ]
