# Generated by Django 5.0.4 on 2024-05-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_alter_mail_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail_periodicity',
            field=models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', verbose_name='Статус отправки'),
        ),
    ]
