# Generated by Django 5.0.4 on 2024-05-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_logattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mail_datetime_last',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя дата отправки рассылки'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начало отправки рассылки'),
        ),
    ]
