# Generated by Django 5.0.4 on 2024-05-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_mail_mail_datetime_last_alter_mail_mail_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail_datetime',
            field=models.DateTimeField(verbose_name='Начало отправки рассылки'),
        ),
    ]
