# Generated by Django 5.0.4 on 2024-05-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_alter_mail_mail_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mail_active',
            field=models.BooleanField(default=True, verbose_name='Активность рассылки'),
        ),
    ]
