# Generated by Django 5.0.4 on 2024-05-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_mail_mail_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='client',
            field=models.ManyToManyField(related_name='client', to='newsletter.client', verbose_name='Клиент'),
        ),
    ]
