# Generated by Django 4.2.2 on 2024-05-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0013_client_owner_mail_owner_message_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='mail_status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', verbose_name='Статус отправки'),
        ),
    ]
