# Generated by Django 4.2.2 on 2024-05-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0014_alter_mail_mail_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'permissions': [('set_activation_mail', 'Can deactivate a mail')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
